# Generated by Django 4.1 on 2022-09-17 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='I forgot to add heading..', max_length=55)),
                ('urll', models.CharField(default='www. .com', max_length=55)),
                ('slug', models.SlugField()),
                ('body', models.TextField(blank=True, default='', max_length=999, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagemjko')),
                ('details', models.TextField(blank=True, null=True)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='imagevfrd')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='imagebhyughn')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='I forgot to add heading..', max_length=55)),
                ('body', models.TextField(blank=True, default='', max_length=999, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='I forgot to add heading..', max_length=55)),
                ('body', models.TextField(blank=True, default='', max_length=999, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='image/')),
                ('urll', models.CharField(default='www. .com', max_length=55)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='imagea')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='imagess')),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
